name: age_counter
version: 1.0.0+1

description: "A simple Flutter app to demonstrate Provider state management with age milestones."
publish_to: 'none'

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  window_size: 0.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

